import axios from '../config/axios.config';
import { API_ENDPOINTS } from '../constants/api';

// https://api.devsnest.in/api/v1/contents?filter[data_type]=question&filter[parent_id]=warmup,arrays
export const getQuestions = async (options = {}) => {
  if (process.env.REACT_APP_MOCK_API) {
    const params = getParams(options);
    console.log('xxxxxxxxxxxxxxxxxxxx', { params });
    const response = await axios.get(API_ENDPOINTS.CONTENTS, { params });
    return response.data;
  } else return (await fakeQuestionData()).data;
};

const getParams = (options = {}) => {
  const { topics, difficulty, question_type, data_type } = options;
  const params = {};
  params[`filter[data_type]`] = 'question';
  if (data_type) params[`filter[data_type]`] = data_type;
  if (difficulty) params[`filter[difficulty]`] = difficulty;
  if (question_type) params[`filter[question_type]`] = question_type;

  if (topics && topics.length > 0) {
    // parent_id is the list of topics selected seperated by a comma
    const topicStringified = joinArray(topics.map((topic) => topic.name));
    params[`filter[parent_id]`] = topicStringified;
  }
  return params;
};

const joinArray = (list) => {
  return list.join(',');
};

const fakeQuestionData = () => {
  const rejectAPI = Math.random() < 0.1;
  return new Promise((res, rej) => {
    setTimeout(() => {
      rejectAPI
        ? rej({
            error: 'some error occured',
          })
        : res({
            data: [
              {
                id: '1',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/1',
                },
                attributes: {
                  unique_id: 'fend',
                  parent_id: null,
                  name: 'frontend',
                  data_type: 'topic',
                  link: null,
                  priority: 0,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '2',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/2',
                },
                attributes: {
                  unique_id: 'html',
                  parent_id: 'fend',
                  name: 'HTML',
                  data_type: 'subtopic',
                  link: null,
                  priority: 1,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '3',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/3',
                },
                attributes: {
                  unique_id: 'YT1',
                  parent_id: 'html',
                  name: 'Frontend Day 1 - Introduction to HTML',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=KnZa_Ri_B18&t=1378s',
                  priority: 2,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 14,
                      unique_id: 'Q1',
                      parent_id: 'YT1',
                      name: 'question 1',
                      data_type: 'question',
                      link:
                        'https://drive.google.com/file/d/1KiZnTNhUaQpeIkRcvvsbGrR1SxF9Urhf/view',
                      priority: 13,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.128+05:30',
                      updated_at: '2021-07-02T14:12:23.128+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/yeyeyeye',
                    },
                  ],
                  video_questions: [14],
                },
              },
              {
                id: '4',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/4',
                },
                attributes: {
                  unique_id: 'css',
                  parent_id: 'fend',
                  name: 'Css',
                  data_type: 'subtopic',
                  link: null,
                  priority: 3,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '5',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/5',
                },
                attributes: {
                  unique_id: 'YT2',
                  parent_id: 'css',
                  name: 'Frontend Day 2 - Introduction to CSS',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=porf5cZwExI',
                  priority: 4,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 15,
                      unique_id: 'Q2',
                      parent_id: 'YT2',
                      name: 'question 2',
                      data_type: 'question',
                      link:
                        'https://drive.google.com/file/d/1KiZnTNhUaQpeIkRcvvsbGrR1SxF9Urhf/view',
                      priority: 14,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.158+05:30',
                      updated_at: '2021-07-02T14:12:23.158+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/hi',
                    },
                  ],
                  video_questions: [15],
                },
              },
              {
                id: '6',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/6',
                },
                attributes: {
                  unique_id: 'YT3',
                  parent_id: 'css',
                  name: 'Frontend Day 3 - Continuing with CSS',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=EmXf7YcFmhs&t=2096s',
                  priority: 5,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 16,
                      unique_id: 'Q3',
                      parent_id: 'YT3',
                      name: 'question 3',
                      data_type: 'question',
                      link:
                        'https://drive.google.com/file/d/1htU3hI1chl4dPbxKuwp7SxM6UsQ5fyMF/view',
                      priority: 15,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.173+05:30',
                      updated_at: '2021-07-02T14:12:23.173+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/dsa',
                    },
                  ],
                  video_questions: [16],
                },
              },
              {
                id: '7',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/7',
                },
                attributes: {
                  unique_id: 'YT4',
                  parent_id: 'css',
                  name: 'Frontend Day 4 - Positions | Display | Overflow',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=Tl2yie4qDLQ&t=2550s',
                  priority: 6,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 17,
                      unique_id: 'Q4',
                      parent_id: 'YT4',
                      name: 'question 4',
                      data_type: 'question',
                      link:
                        'https://drive.google.com/file/d/1P08tbZMr_7A2y46rRsFQWEGEyqIZhuQ8/view',
                      priority: 16,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.196+05:30',
                      updated_at: '2021-07-02T14:12:23.196+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'null',
                    },
                  ],
                  video_questions: [17],
                },
              },
              {
                id: '8',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/8',
                },
                attributes: {
                  unique_id: 'js',
                  parent_id: 'fend',
                  name: 'Javascript',
                  data_type: 'subtopic',
                  link: null,
                  priority: 7,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '9',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/9',
                },
                attributes: {
                  unique_id: 'YT5',
                  parent_id: 'js',
                  name: 'Frontend Day 5 - Introduction to Javascript',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=KCPkrGCq9B8&t=3707s',
                  priority: 8,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '10',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/10',
                },
                attributes: {
                  unique_id: 'YT6',
                  parent_id: 'js',
                  name: 'Frontend Day 6 - Arrays | Introduction to Javascript',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=Yxj54m8dGNg',
                  priority: 9,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 18,
                      unique_id: 'Q5',
                      parent_id: 'YT6',
                      name: 'question 5',
                      data_type: 'question',
                      link:
                        'https://docs.google.com/document/d/1ocDYa2B27H2tZVI7f_i-7Ze6SIX_2g2N-jUJJ9t__0g/edit',
                      priority: 17,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.213+05:30',
                      updated_at: '2021-07-02T14:12:23.213+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'null',
                    },
                  ],
                  video_questions: [18],
                },
              },
              {
                id: '11',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/11',
                },
                attributes: {
                  unique_id: 'YT7',
                  parent_id: 'js',
                  name: 'Frontend Day 7 - Objects | Introduction to Javascript',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=_eSDbbGmgAU',
                  priority: 10,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 19,
                      unique_id: 'Q6',
                      parent_id: 'YT7',
                      name: 'question 6',
                      data_type: 'question',
                      link:
                        'https://docs.google.com/document/d/1ElC4HVna2FO6SqeSd2zuUEuIC2CnnQQqsnOTpL9hydk/edit',
                      priority: 18,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.248+05:30',
                      updated_at: '2021-07-02T14:12:23.248+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/str66',
                    },
                  ],
                  video_questions: [19],
                },
              },
              {
                id: '12',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/12',
                },
                attributes: {
                  unique_id: 'YT8',
                  parent_id: 'js',
                  name: 'Frontend Day 8 - Objects | Introduction to Javascript',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=2eDK5zWjR64&t=5s',
                  priority: 11,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 20,
                      unique_id: 'Q7',
                      parent_id: 'YT8',
                      name: 'question 7',
                      data_type: 'question',
                      link: 'https://100dayscss.com/?dayIndex=46',
                      priority: 19,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.270+05:30',
                      updated_at: '2021-07-02T14:12:23.270+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/helloxd',
                    },
                  ],
                  video_questions: [20],
                },
              },
              {
                id: '13',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/13',
                },
                attributes: {
                  unique_id: 'YT9',
                  parent_id: 'js',
                  name: 'Frontend Day 9 | this Keyword | Call | Apply | Bind',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=j9gacsYnjWE',
                  priority: 12,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 21,
                      unique_id: 'Q8',
                      parent_id: 'YT9',
                      name: 'question 8',
                      data_type: 'question',
                      link:
                        'https://docs.google.com/document/d/1guR5EqC4HzMyfgBxr8z_U_EM0ZNDJZsBLg__taRSnOA/edit',
                      priority: 20,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.286+05:30',
                      updated_at: '2021-07-02T14:12:23.286+05:30',
                      score: null,
                      difficulty: null,
                      question_type: null,
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'https://github.com/yoyoyyoyoy',
                    },
                  ],
                  video_questions: [21],
                },
              },
              {
                id: '14',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/14',
                },
                attributes: {
                  unique_id: 'Q1',
                  parent_id: 'YT1',
                  name: 'question 1',
                  data_type: 'question',
                  link:
                    'https://drive.google.com/file/d/1KiZnTNhUaQpeIkRcvvsbGrR1SxF9Urhf/view',
                  priority: 13,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/yeyeyeye',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '15',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/15',
                },
                attributes: {
                  unique_id: 'Q2',
                  parent_id: 'YT2',
                  name: 'question 2',
                  data_type: 'question',
                  link:
                    'https://drive.google.com/file/d/1KiZnTNhUaQpeIkRcvvsbGrR1SxF9Urhf/view',
                  priority: 14,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/hi',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '16',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/16',
                },
                attributes: {
                  unique_id: 'Q3',
                  parent_id: 'YT3',
                  name: 'question 3',
                  data_type: 'question',
                  link:
                    'https://drive.google.com/file/d/1htU3hI1chl4dPbxKuwp7SxM6UsQ5fyMF/view',
                  priority: 15,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/dsa',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '17',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/17',
                },
                attributes: {
                  unique_id: 'Q4',
                  parent_id: 'YT4',
                  name: 'question 4',
                  data_type: 'question',
                  link:
                    'https://drive.google.com/file/d/1P08tbZMr_7A2y46rRsFQWEGEyqIZhuQ8/view',
                  priority: 16,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '18',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/18',
                },
                attributes: {
                  unique_id: 'Q5',
                  parent_id: 'YT6',
                  name: 'question 5',
                  data_type: 'question',
                  link:
                    'https://docs.google.com/document/d/1ocDYa2B27H2tZVI7f_i-7Ze6SIX_2g2N-jUJJ9t__0g/edit',
                  priority: 17,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '19',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/19',
                },
                attributes: {
                  unique_id: 'Q6',
                  parent_id: 'YT7',
                  name: 'question 6',
                  data_type: 'question',
                  link:
                    'https://docs.google.com/document/d/1ElC4HVna2FO6SqeSd2zuUEuIC2CnnQQqsnOTpL9hydk/edit',
                  priority: 18,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/str66',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '20',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/20',
                },
                attributes: {
                  unique_id: 'Q7',
                  parent_id: 'YT8',
                  name: 'question 7',
                  data_type: 'question',
                  link: 'https://100dayscss.com/?dayIndex=46',
                  priority: 19,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/helloxd',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '21',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/21',
                },
                attributes: {
                  unique_id: 'Q8',
                  parent_id: 'YT9',
                  name: 'question 8',
                  data_type: 'question',
                  link:
                    'https://docs.google.com/document/d/1guR5EqC4HzMyfgBxr8z_U_EM0ZNDJZsBLg__taRSnOA/edit',
                  priority: 20,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: 'https://github.com/yoyoyyoyoy',
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '22',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/22',
                },
                attributes: {
                  unique_id: 'algo',
                  parent_id: null,
                  name: 'Algorithims',
                  data_type: 'topic',
                  link: null,
                  priority: 21,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '23',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/23',
                },
                attributes: {
                  unique_id: 'arrays',
                  parent_id: 'algo',
                  name: 'Arrays',
                  data_type: 'subtopic',
                  link: null,
                  priority: 22,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '29',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/29',
                },
                attributes: {
                  unique_id: 'bst',
                  parent_id: 'algo',
                  name: 'Arrays',
                  data_type: 'subtopic',
                  link: null,
                  priority: 22,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '24',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/24',
                },
                attributes: {
                  unique_id: 'Q9',
                  parent_id: 'arrays',
                  name: 'Two Sum',
                  data_type: 'question',
                  link: 'https://leetcode.com/problems/two-sum/',
                  priority: 23,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'class',
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '30',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/30',
                },
                attributes: {
                  unique_id: 'Q13',
                  parent_id: 'bst',
                  name: 'Two Sum',
                  data_type: 'question',
                  link: 'https://leetcode.com/problems/two-sum/',
                  priority: 23,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'class',
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '25',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/25',
                },
                attributes: {
                  unique_id: 'Q10',
                  parent_id: 'arrays',
                  name: ' Product of Array Except Self',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/product-of-array-except-self/',
                  priority: 24,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'assignment',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '31',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/31',
                },
                attributes: {
                  unique_id: 'Q14',
                  parent_id: 'bst',
                  name: ' Product of Array Except Self',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/product-of-array-except-self/',
                  priority: 24,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'assignment',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '26',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/26',
                },
                attributes: {
                  unique_id: 'Q11',
                  parent_id: 'arrays',
                  name: 'Best Time to Buy and Sell Stock',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
                  priority: 25,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'class',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '32',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/32',
                },
                attributes: {
                  unique_id: 'Q15',
                  parent_id: 'bst',
                  name: 'Best Time to Buy and Sell Stock',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
                  priority: 25,
                  score: null,
                  difficulty: 'easy',
                  question_type: 'class',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '27',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/27',
                },
                attributes: {
                  unique_id: 'Q12',
                  parent_id: 'arrays',
                  name: 'Median of Two Sorted Arrays',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/median-of-two-sorted-arrays/',
                  priority: 26,
                  score: null,
                  difficulty: 'hard',
                  question_type: 'assignment',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '33',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/33',
                },
                attributes: {
                  unique_id: 'Q16',
                  parent_id: 'bst',
                  name: 'Median of Two Sorted Arrays',
                  data_type: 'question',
                  link:
                    'https://leetcode.com/problems/median-of-two-sorted-arrays/',
                  priority: 26,
                  score: null,
                  difficulty: 'hard',
                  question_type: 'assignment',
                  reference_data: null,
                  status: 'done',
                  submission_link: null,
                  questions_list: [],
                  video_questions: null,
                },
              },
              {
                id: '28',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/28',
                },
                attributes: {
                  unique_id: 'YT12',
                  parent_id: 'arrays',
                  name:
                    'DSA | Day 1 | Arrays | Two Sum , Best Time to Buy and Sell Stock',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=OSQk34Rtgx0',
                  priority: 27,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 24,
                      unique_id: 'Q9',
                      parent_id: 'arrays',
                      name: 'Two Sum',
                      data_type: 'question',
                      link: 'https://leetcode.com/problems/two-sum/',
                      priority: 23,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.349+05:30',
                      updated_at: '2021-07-02T14:12:23.349+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'class',
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'null',
                    },
                    {
                      id: 25,
                      unique_id: 'Q10',
                      parent_id: 'arrays',
                      name: ' Product of Array Except Self',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/product-of-array-except-self/',
                      priority: 24,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.367+05:30',
                      updated_at: '2021-07-02T14:12:23.367+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'assignment',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                    {
                      id: 26,
                      unique_id: 'Q11',
                      parent_id: 'arrays',
                      name: 'Best Time to Buy and Sell Stock',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
                      priority: 25,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.389+05:30',
                      updated_at: '2021-07-02T14:12:23.389+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'class',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                    {
                      id: 27,
                      unique_id: 'Q12',
                      parent_id: 'arrays',
                      name: 'Median of Two Sorted Arrays',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/median-of-two-sorted-arrays/',
                      priority: 26,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.406+05:30',
                      updated_at: '2021-07-02T14:12:23.406+05:30',
                      score: null,
                      difficulty: 'hard',
                      question_type: 'assignment',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                  ],
                  video_questions: [24, 25, 26, 27],
                },
              },
              {
                id: '34',
                type: 'contents',
                links: {
                  self: 'http://localhost:8000/api/v1/contents/34',
                },
                attributes: {
                  unique_id: 'YT11',
                  parent_id: 'bst',
                  name: 'DSA | Day 12 | BST | QuestionXYZ',
                  data_type: 'video',
                  link: 'https://www.youtube.com/watch?v=kp1qG3OhqlE',
                  priority: 27,
                  score: null,
                  difficulty: null,
                  question_type: null,
                  reference_data: null,
                  status: 'notdone',
                  submission_link: null,
                  questions_list: [
                    {
                      id: 30,
                      unique_id: 'Q13',
                      parent_id: 'bst',
                      name: 'Two Sum',
                      data_type: 'question',
                      link: 'https://leetcode.com/problems/two-sum/',
                      priority: 23,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.440+05:30',
                      updated_at: '2021-07-02T14:12:23.440+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'class',
                      video_questions: null,
                      reference_data: null,
                      status: 'notdone',
                      submission_link: 'null',
                    },
                    {
                      id: 31,
                      unique_id: 'Q14',
                      parent_id: 'bst',
                      name: ' Product of Array Except Self',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/product-of-array-except-self/',
                      priority: 24,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.452+05:30',
                      updated_at: '2021-07-02T14:12:23.452+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'assignment',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                    {
                      id: 32,
                      unique_id: 'Q15',
                      parent_id: 'bst',
                      name: 'Best Time to Buy and Sell Stock',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
                      priority: 25,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.463+05:30',
                      updated_at: '2021-07-02T14:12:23.463+05:30',
                      score: null,
                      difficulty: 'easy',
                      question_type: 'class',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                    {
                      id: 33,
                      unique_id: 'Q16',
                      parent_id: 'bst',
                      name: 'Median of Two Sorted Arrays',
                      data_type: 'question',
                      link:
                        'https://leetcode.com/problems/median-of-two-sorted-arrays/',
                      priority: 26,
                      extra_link1: null,
                      extra_link2: null,
                      created_at: '2021-07-02T14:12:23.475+05:30',
                      updated_at: '2021-07-02T14:12:23.475+05:30',
                      score: null,
                      difficulty: 'hard',
                      question_type: 'assignment',
                      video_questions: null,
                      reference_data: null,
                      status: 'done',
                      submission_link: 'null',
                    },
                  ],
                  video_questions: [30, 31, 32, 33],
                },
              },
            ],
          });
    }, 1000);
  });
};
