name: Check Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: 'Install yarn'
        run: npm i -g yarn && yarn
      - name: 'Install dependencies'
        run: yarn
      - name: Verify linting
        run: yarn verify
